package com.eai.service.mq.poller;

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.07 at 11:27:13 PM IST 
//

import java.util.ArrayList;
import java.util.List;

/*import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;*/
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaInfo">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ChannelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CircleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IsPostpaid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SRCreateRequest">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="p_user_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_type_val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_subtype_val" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_cellno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute4" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute5" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute6" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute7" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute8" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute9" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute10" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute11" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute12" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute13" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute14" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute15" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_attribute16" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_media" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_create_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p_circle_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="error_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Output">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="incident_numbers">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="p_incident_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="error_desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "metaInfo", "srCreateRequest" })
@XmlRootElement(name = "CreateRequest")
public class CreateRequest {

	/*
	 * @Override public String toString() {
	 * 
	 * String xml = null;
	 * 
	 * try { JAXBContext jaxbContext = JAXBContext.newInstance(CreateRequest.class);
	 * Marshaller marshaller = jaxbContext.createMarshaller();
	 * marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, true);
	 * ByteArrayOutputStream out = new ByteArrayOutputStream();
	 * marshaller.marshal(this, out); xml = new String(out.toByteArray()); } catch
	 * (JAXBException e) { xml = e.toString(); }
	 * 
	 * return xml; }
	 */
	@XmlElement(name = "MetaInfo", required = true)
	protected CreateRequest.MetaInfo metaInfo;
	@XmlElement(name = "SRCreateRequest", required = true)
	protected CreateRequest.SRCreateRequest srCreateRequest;

	/**
	 * Gets the value of the metaInfo property.
	 * 
	 * @return possible object is {@link CreateRequest.MetaInfo }
	 * 
	 */
	public CreateRequest.MetaInfo getMetaInfo() {
		return metaInfo;
	}

	/**
	 * Sets the value of the metaInfo property.
	 * 
	 * @param value allowed object is {@link CreateRequest.MetaInfo }
	 * 
	 */
	public void setMetaInfo(CreateRequest.MetaInfo value) {
		this.metaInfo = value;
	}

	/**
	 * Gets the value of the srCreateRequest property.
	 * 
	 * @return possible object is {@link CreateRequest.SRCreateRequest }
	 * 
	 */
	public CreateRequest.SRCreateRequest getSRCreateRequest() {
		return srCreateRequest;
	}

	/**
	 * Sets the value of the srCreateRequest property.
	 * 
	 * @param value allowed object is {@link CreateRequest.SRCreateRequest }
	 * 
	 */
	public void setSRCreateRequest(CreateRequest.SRCreateRequest value) {
		this.srCreateRequest = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="ServiceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="ChannelName" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="CircleId" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="IsPostpaid" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "serviceName", "channelName", "circleId", "isPostpaid", "key" })
	public static class MetaInfo {

		@XmlElement(name = "ServiceName", required = true)
		protected String serviceName;
		@XmlElement(name = "ChannelName", required = true)
		protected String channelName;
		@XmlElement(name = "CircleId", required = true)
		protected String circleId;
		@XmlElement(name = "IsPostpaid", required = true)
		protected String isPostpaid;
		@XmlElement(name = "Key")
		protected List<String> key;

		/**
		 * Gets the value of the serviceName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getServiceName() {
			return serviceName;
		}

		/**
		 * Sets the value of the serviceName property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setServiceName(String value) {
			this.serviceName = value;
		}

		/**
		 * Gets the value of the channelName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getChannelName() {
			return channelName;
		}

		/**
		 * Sets the value of the channelName property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setChannelName(String value) {
			this.channelName = value;
		}

		/**
		 * Gets the value of the circleId property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getCircleId() {
			return circleId;
		}

		/**
		 * Sets the value of the circleId property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setCircleId(String value) {
			this.circleId = value;
		}

		/**
		 * Gets the value of the isPostpaid property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getIsPostpaid() {
			return isPostpaid;
		}

		/**
		 * Sets the value of the isPostpaid property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setIsPostpaid(String value) {
			this.isPostpaid = value;
		}

		/**
		 * Gets the value of the key property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a snapshot.
		 * Therefore any modification you make to the returned list will be present
		 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
		 * for the key property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getKey().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list {@link String }
		 * 
		 * 
		 */
		public List<String> getKey() {
			if (key == null) {
				key = new ArrayList<String>();
			}
			return this.key;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained within
	 * this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="p_user_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_type_val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_subtype_val" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_cellno" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute1" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute2" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute3" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute4" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute5" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute6" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute7" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute8" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute9" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute10" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute11" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute12" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute13" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute14" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute15" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_attribute16" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_media" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_create_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="p_circle_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="error_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Output">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="incident_numbers">
	 *                     &lt;complexType>
	 *                       &lt;complexContent>
	 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                           &lt;sequence>
	 *                             &lt;element name="p_incident_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                           &lt;/sequence>
	 *                         &lt;/restriction>
	 *                       &lt;/complexContent>
	 *                     &lt;/complexType>
	 *                   &lt;/element>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *         &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="error_desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "pUserName", "pTypeVal", "pSubtypeVal", "pCellno", "pAttribute1", "pAttribute2",
			"pAttribute3", "pAttribute4", "pAttribute5", "pAttribute6", "pAttribute7", "pAttribute8", "pAttribute9",
			"pAttribute10", "pAttribute11", "pAttribute12", "pAttribute13", "pAttribute14", "pAttribute15",
			"pAttribute16", "pMedia", "pCreateDate", "pCircleId", "errorStatus", "output", "errorCode", "errorDesc" })
	public static class SRCreateRequest {

		@XmlElement(name = "p_user_name", required = true)
		protected String pUserName;
		@XmlElement(name = "p_type_val", required = true)
		protected String pTypeVal;
		@XmlElement(name = "p_subtype_val", required = true)
		protected String pSubtypeVal;
		@XmlElement(name = "p_cellno", required = true)
		protected String pCellno;
		@XmlElement(name = "p_attribute1", required = true)
		protected String pAttribute1;
		@XmlElement(name = "p_attribute2", required = true)
		protected String pAttribute2;
		@XmlElement(name = "p_attribute3", required = true)
		protected String pAttribute3;
		@XmlElement(name = "p_attribute4", required = true)
		protected String pAttribute4;
		@XmlElement(name = "p_attribute5", required = true)
		protected String pAttribute5;
		@XmlElement(name = "p_attribute6", required = true)
		protected String pAttribute6;
		@XmlElement(name = "p_attribute7", required = true)
		protected String pAttribute7;
		@XmlElement(name = "p_attribute8", required = true)
		protected String pAttribute8;
		@XmlElement(name = "p_attribute9", required = true)
		protected String pAttribute9;
		@XmlElement(name = "p_attribute10", required = true)
		protected String pAttribute10;
		@XmlElement(name = "p_attribute11", required = true)
		protected String pAttribute11;
		@XmlElement(name = "p_attribute12", required = true)
		protected String pAttribute12;
		@XmlElement(name = "p_attribute13", required = true)
		protected String pAttribute13;
		@XmlElement(name = "p_attribute14", required = true)
		protected String pAttribute14;
		@XmlElement(name = "p_attribute15", required = true)
		protected String pAttribute15;
		@XmlElement(name = "p_attribute16", required = true)
		protected String pAttribute16;
		@XmlElement(name = "p_media", required = true)
		protected String pMedia;
		@XmlElement(name = "p_create_date", required = true)
		protected String pCreateDate;
		@XmlElement(name = "p_circle_id", required = true)
		protected String pCircleId;
		@XmlElement(name = "error_status", required = true)
		protected String errorStatus;
		@XmlElement(name = "Output", required = true)
		protected CreateRequest.SRCreateRequest.Output output;
		@XmlElement(name = "error_code", required = true)
		protected String errorCode;
		@XmlElement(name = "error_desc", required = true)
		protected String errorDesc;

		/**
		 * Gets the value of the pUserName property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPUserName() {
			return pUserName;
		}

		/**
		 * Sets the value of the pUserName property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPUserName(String value) {
			this.pUserName = value;
		}

		/**
		 * Gets the value of the pTypeVal property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPTypeVal() {
			return pTypeVal;
		}

		/**
		 * Sets the value of the pTypeVal property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPTypeVal(String value) {
			this.pTypeVal = value;
		}

		/**
		 * Gets the value of the pSubtypeVal property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPSubtypeVal() {
			return pSubtypeVal;
		}

		/**
		 * Sets the value of the pSubtypeVal property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPSubtypeVal(String value) {
			this.pSubtypeVal = value;
		}

		/**
		 * Gets the value of the pCellno property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPCellno() {
			return pCellno;
		}

		/**
		 * Sets the value of the pCellno property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPCellno(String value) {
			this.pCellno = value;
		}

		/**
		 * Gets the value of the pAttribute1 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute1() {
			return pAttribute1;
		}

		/**
		 * Sets the value of the pAttribute1 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute1(String value) {
			this.pAttribute1 = value;
		}

		/**
		 * Gets the value of the pAttribute2 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute2() {
			return pAttribute2;
		}

		/**
		 * Sets the value of the pAttribute2 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute2(String value) {
			this.pAttribute2 = value;
		}

		/**
		 * Gets the value of the pAttribute3 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute3() {
			return pAttribute3;
		}

		/**
		 * Sets the value of the pAttribute3 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute3(String value) {
			this.pAttribute3 = value;
		}

		/**
		 * Gets the value of the pAttribute4 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute4() {
			return pAttribute4;
		}

		/**
		 * Sets the value of the pAttribute4 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute4(String value) {
			this.pAttribute4 = value;
		}

		/**
		 * Gets the value of the pAttribute5 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute5() {
			return pAttribute5;
		}

		/**
		 * Sets the value of the pAttribute5 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute5(String value) {
			this.pAttribute5 = value;
		}

		/**
		 * Gets the value of the pAttribute6 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute6() {
			return pAttribute6;
		}

		/**
		 * Sets the value of the pAttribute6 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute6(String value) {
			this.pAttribute6 = value;
		}

		/**
		 * Gets the value of the pAttribute7 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute7() {
			return pAttribute7;
		}

		/**
		 * Sets the value of the pAttribute7 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute7(String value) {
			this.pAttribute7 = value;
		}

		/**
		 * Gets the value of the pAttribute8 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute8() {
			return pAttribute8;
		}

		/**
		 * Sets the value of the pAttribute8 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute8(String value) {
			this.pAttribute8 = value;
		}

		/**
		 * Gets the value of the pAttribute9 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute9() {
			return pAttribute9;
		}

		/**
		 * Sets the value of the pAttribute9 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute9(String value) {
			this.pAttribute9 = value;
		}

		/**
		 * Gets the value of the pAttribute10 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute10() {
			return pAttribute10;
		}

		/**
		 * Sets the value of the pAttribute10 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute10(String value) {
			this.pAttribute10 = value;
		}

		/**
		 * Gets the value of the pAttribute11 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute11() {
			return pAttribute11;
		}

		/**
		 * Sets the value of the pAttribute11 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute11(String value) {
			this.pAttribute11 = value;
		}

		/**
		 * Gets the value of the pAttribute12 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute12() {
			return pAttribute12;
		}

		/**
		 * Sets the value of the pAttribute12 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute12(String value) {
			this.pAttribute12 = value;
		}

		/**
		 * Gets the value of the pAttribute13 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute13() {
			return pAttribute13;
		}

		/**
		 * Sets the value of the pAttribute13 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute13(String value) {
			this.pAttribute13 = value;
		}

		/**
		 * Gets the value of the pAttribute14 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute14() {
			return pAttribute14;
		}

		/**
		 * Sets the value of the pAttribute14 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute14(String value) {
			this.pAttribute14 = value;
		}

		/**
		 * Gets the value of the pAttribute15 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute15() {
			return pAttribute15;
		}

		/**
		 * Sets the value of the pAttribute15 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute15(String value) {
			this.pAttribute15 = value;
		}

		/**
		 * Gets the value of the pAttribute16 property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPAttribute16() {
			return pAttribute16;
		}

		/**
		 * Sets the value of the pAttribute16 property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPAttribute16(String value) {
			this.pAttribute16 = value;
		}

		/**
		 * Gets the value of the pMedia property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPMedia() {
			return pMedia;
		}

		/**
		 * Sets the value of the pMedia property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPMedia(String value) {
			this.pMedia = value;
		}

		/**
		 * Gets the value of the pCreateDate property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPCreateDate() {
			return pCreateDate;
		}

		/**
		 * Sets the value of the pCreateDate property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPCreateDate(String value) {
			this.pCreateDate = value;
		}

		/**
		 * Gets the value of the pCircleId property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getPCircleId() {
			return pCircleId;
		}

		/**
		 * Sets the value of the pCircleId property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setPCircleId(String value) {
			this.pCircleId = value;
		}

		/**
		 * Gets the value of the errorStatus property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getErrorStatus() {
			return errorStatus;
		}

		/**
		 * Sets the value of the errorStatus property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setErrorStatus(String value) {
			this.errorStatus = value;
		}

		/**
		 * Gets the value of the output property.
		 * 
		 * @return possible object is {@link CreateRequest.SRCreateRequest.Output }
		 * 
		 */
		public CreateRequest.SRCreateRequest.Output getOutput() {
			return output;
		}

		/**
		 * Sets the value of the output property.
		 * 
		 * @param value allowed object is {@link CreateRequest.SRCreateRequest.Output }
		 * 
		 */
		public void setOutput(CreateRequest.SRCreateRequest.Output value) {
			this.output = value;
		}

		/**
		 * Gets the value of the errorCode property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getErrorCode() {
			return errorCode;
		}

		/**
		 * Sets the value of the errorCode property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setErrorCode(String value) {
			this.errorCode = value;
		}

		/**
		 * Gets the value of the errorDesc property.
		 * 
		 * @return possible object is {@link String }
		 * 
		 */
		public String getErrorDesc() {
			return errorDesc;
		}

		/**
		 * Sets the value of the errorDesc property.
		 * 
		 * @param value allowed object is {@link String }
		 * 
		 */
		public void setErrorDesc(String value) {
			this.errorDesc = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content contained within
		 * this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="incident_numbers">
		 *           &lt;complexType>
		 *             &lt;complexContent>
		 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *                 &lt;sequence>
		 *                   &lt;element name="p_incident_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *                 &lt;/sequence>
		 *               &lt;/restriction>
		 *             &lt;/complexContent>
		 *           &lt;/complexType>
		 *         &lt;/element>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "incidentNumbers" })
		public static class Output {

			@XmlElement(name = "incident_numbers", required = true)
			protected CreateRequest.SRCreateRequest.Output.IncidentNumbers incidentNumbers;

			/**
			 * Gets the value of the incidentNumbers property.
			 * 
			 * @return possible object is
			 *         {@link CreateRequest.SRCreateRequest.Output.IncidentNumbers }
			 * 
			 */
			public CreateRequest.SRCreateRequest.Output.IncidentNumbers getIncidentNumbers() {
				return incidentNumbers;
			}

			/**
			 * Sets the value of the incidentNumbers property.
			 * 
			 * @param value allowed object is
			 *              {@link CreateRequest.SRCreateRequest.Output.IncidentNumbers }
			 * 
			 */
			public void setIncidentNumbers(CreateRequest.SRCreateRequest.Output.IncidentNumbers value) {
				this.incidentNumbers = value;
			}

			/**
			 * <p>
			 * Java class for anonymous complex type.
			 * 
			 * <p>
			 * The following schema fragment specifies the expected content contained within
			 * this class.
			 * 
			 * <pre>
			 * &lt;complexType>
			 *   &lt;complexContent>
			 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
			 *       &lt;sequence>
			 *         &lt;element name="p_incident_no" type="{http://www.w3.org/2001/XMLSchema}string"/>
			 *       &lt;/sequence>
			 *     &lt;/restriction>
			 *   &lt;/complexContent>
			 * &lt;/complexType>
			 * </pre>
			 * 
			 * 
			 */
			@XmlAccessorType(XmlAccessType.FIELD)
			@XmlType(name = "", propOrder = { "pIncidentNo" })
			public static class IncidentNumbers {

				@XmlElement(name = "p_incident_no", required = true)
				protected String pIncidentNo;

				/**
				 * Gets the value of the pIncidentNo property.
				 * 
				 * @return possible object is {@link String }
				 * 
				 */
				public String getPIncidentNo() {
					return pIncidentNo;
				}

				/**
				 * Sets the value of the pIncidentNo property.
				 * 
				 * @param value allowed object is {@link String }
				 * 
				 */
				public void setPIncidentNo(String value) {
					this.pIncidentNo = value;
				}

			}

		}

	}

}
